# Generated by Django 3.2.3 on 2021-06-18 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='customer',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='customer',
            new_name='cliente',
        ),
        migrations.DeleteModel(
            name='tarjeta',
        ),
    ]
