# Generated by Django 3.2.3 on 2021-06-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210618_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='descripcion'),
        ),
    ]
